version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5555:5432'
    volumes:
      - ecou:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8090
volumes:
  redis:
    driver: local
  ecou:

